### PR TITLE
fix line breaks

### PR DESCRIPTION
**Pull request by gj**

### CODE REVIEW

**Comment by pletcher** [comment]
Thanks for taking the time to make this PR, @ga-be -- but for now, I'm going to close it, as this is an issue with Learn's markdown implementation and not with the curriculum itself.

The line breaks make it _much_ simpler to look through commit history for changes. And while I understand that there's no "Markdown spec" per se, it seems safe to stick to GFM, which does not treat single newlines as new paragraphs.

**Comment by gj** [comment]
Thanks for the clarification @pletcher ! Will keep that in mind going forward.

What do you think about making lib/book.rb blank to match its state in the README directions: https://github.com/learn-co-curriculum/oo-basics/pull/25/commits/32591439f1ef42d40dec8e875b91d658c3bcd0ba

**Comment by pletcher** [comment]
We can definitely do that :)

Want to submit a PR?

**Comment by pletcher** [comment]
Just saw your PR -- thanks!

**Comment by gj** [comment]
You're welcome!

**Pull request closed without merging**
